### ISSUE TITLE
Part 2, Chapter 3 - Developing and testing service functions - NODE_OPTIONS is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mathorin** [PacktPublishing/Modern-Full-Stack-React-Projects#86]
In chapter 3 - Implementing a Backend..., section "Developing and testing service functions" when running 'npm test' (step 14) I received an error: 'NODE_OPTIONS' is not recognized as an internal or external command, operable program or batch file.

_This is likely because I am running on Windows, VSCode, using the VSCode integrated terminal and the issue may not occur on MacOS or Linux systems or possibly using Powershell under Windows_

To fix this, I installed cross-env from the terminal using the command: 

`npm i cross-env`

And adding cross-env in step 13, for the test script line which is modified to be:

Step 13
```
  "scripts": {
    "test": "cross-env NODE_OPTIONS=--experimental-vm-modules jest",
    "lint": "eslint src",
    "prepare": "husky install"
  },
```

There may be another or better way to do this, hopefully this will help someone else if they get stuck at this point with the same issue.

**Comment by omnidan** [comment]
@mathorin Thank you for your report and for providing a solution to it! 🙌 

You are right, environment variables do not work like that in Powershell. You can either use "git bash"[^1] (or a similar shell) that supports this kind of syntax, or, as you already mentioned, the `cross-env` package can be used to solve this problem.

If you have any other feedback or queries do not hesitate to reach out to me ☺️ 

[^1]: https://gitforwindows.org
